# 菜单
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  Categories: /categories
  # Github: https://github.com/yuang01
  About: /about
  link: /friends

Github: https://github.com/yuang01

logo: /medias/logo.png
favicon: /favicon.ico # or .png .jpg .svg .gif .jpeg .ico
# 頂部导航固定
headMenuFixed: true

swiper:
  showPrevNext: true # 是否显示左右切换按钮
  showIndicators: true  # 是否显示指示器
  autoplay: true # 是否自动轮播
  loop: true # 让轮播看起来是循环的, 例如false的话，到达最后一个轮播图的时候，右按钮不能点击
  delay: 5000 # 切换延迟时间
  effect: 'slide' # 'fade'
  textAnimated: 'fadeInDown' # 文字动画，属性使用 animate.css, https://daneden.github.io/animate.css/
  textDuration: '0.2s' # 文字动画持续时间（单位秒）
  textDelay: '0.1s' # 文字动画延迟时间（单位秒）

# 图片点击放大功能
fancybox: 
  on: true

# 统计网站访问数量
busuanzi:
  on: true

# 标签页和分类页中，显示这个标签或者分类在文章中出现的次数
show_count: true

# 打赏功能
donate:
  on: true
donate_message: 你的赏识是我前进的动力
# 支付宝打赏图片相对路径
Alipay: '/img/54542.jpg'
# 微信打赏图片相对路径
WeChatpay: '/img/520.jpg'

# 分享功能
sharejs: 
  on: true
  sites: twitter,facebook,google,qq,qzone,wechat,weibo,douban,linkedin

# 点击出现爱心效果
clicklove:
  on: true

# 全文搜索功能
search:
  on: true

# 文章详情页底部显示上一篇文章和下一篇文章
postNav:
  on: true

# 滚动动画，详情参照https://github.com/michalsnik
aos:
  on: true
  animate: 'fade-up' # animate, 更多选项请参考 https://github.com/michalsnik/aos#animations
  offset: 120 # offset (in px) from the original trigger point
  delay: 0 # values from 0 to 3000, with step 50ms
  duration: 400 # values from 0 to 3000, with step 50ms
  easing: 'ease' # default easing for AOS animations
  once: true # whether animation should happen only once - while scrolling down
  mirror: false # whether elements should animate out while scrolling past them
  anchorPlacement: 'top-bottom' # defines which position of the element regarding to window should trigger the animation

toc:
  on: true
  heading: h2, h3, h4

# 音乐
# 是否在首页显示音乐.
music:
  on: true
  title: #非吸底模式有效
    on: true
    show: 听听音乐
  autoHide: true    # hide automaticaly
  server: netease   #require	music platform: netease, tencent, kugou, xiami, baidu
  type: playlist    #require song, playlist, album, search, artist
  id: 442274724     #require	song id / playlist id / album id / search keyword
  fixed: true       # 开启吸底模式
  autoplay: false   # 是否自动播放
  theme: '#42b983'
  loop: 'all'       # 音频循环播放, 可选值: 'all', 'one', 'none'
  order: 'random'   # 音频循环顺序, 可选值: 'list', 'random'
  preload: 'auto'   # 预加载，可选值: 'none', 'metadata', 'auto'
  volume: 0.7       # 默认音量，请注意播放器会记忆用户设置，用户手动设置音量后默认音量即失效
  listFolded: true  # 列表默认折叠
  hideLrc: true     # 隐藏歌词

# coryRyght
#版权信息
copyright:
  on: true

# 文章置顶
tocArticle:
  on: true

# valine 评论
valine:
  on: true
  appid: nmal09L0arSjEFBUUCSpWzyK-gzGzoHsz
  appkey: xiiSst0NtHRg1POFFV32iqKI
  avatar: '' # 匿名者头像选项
  placeholder: '客官，说点什么吧'

# miniValine
miniValine:
  on: false
  appid: nmal09L0arSjEFBUUCSpWzyK-gzGzoHsz
  appkey: xiiSst0NtHRg1POFFV32iqKI
  avatar: '' # 匿名者头像选项
  placeholder: '客官，说点什么吧'

# gitment 评论
gitment:
  on: false
  gitment_owner: '用户名'      #你的 GitHub ID
  gitment_repo: 'yuang01.github.io' #存储评论的 repo
  clientId: '418a1890782d27e5bc5b' #client ID
  clientSecret: '0500f22139fb648833d54076c086c3dd3c2d8ca4'       #client secret

# 来必力评论
livere:
  on: false
  livere_uid: MTAyMC8zNTA1My8xMTU4OA

# 畅言评论
changyan:
  on: false
  appId: cytFT1Bjx
  conf: 3d54029125cc00c10be39c2e23b4b2c7

# gitalk评论
gitalk:
  on: false         # 用来做启用判断可以不用
  owner: 'yuang01'        #Github 用户名,
  repo:  'yuang01.github.io'         #储存评论issue的github仓库名
  admin:   yuang01        #Github 用户名,
  clientID:  '418a1890782d27e5bc5b'      #`Github Application clientID`
  clientSecret:  '0500f22139fb648833d54076c086c3dd3c2d8ca4'  #`Github Application clientSecret`

CDN:
  valine: https://cdn.jsdelivr.net/npm/valine@1/dist/Valine.min.js
